Make it easier to fix typo failures

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -11,7 +11,7 @@ on:
 name: Continuous integration
 permissions:
   contents: read
-  
+
 jobs:
   check:
     name: Rustfmt
@@ -187,7 +187,6 @@ jobs:
       - name: cargo build write-fonts
         run: cargo build -p write-fonts --target wasm32-unknown-unknown
 
-  # If this fails, consider changing your text or adding something to .typos.toml
   typos:
     name: Check for typos
     runs-on: ubuntu-latest
@@ -195,6 +194,11 @@ jobs:
       - uses: actions/checkout@v4
       - name: check typos
         uses: crate-ci/typos@v1.30.2
+      - name: typo instructions
+        if: failure()
+        run: |
+          echo "::error::Fix "check typos" or add an entry in .typos.toml"
+          exit 1
 
   fauntlet:
     name: fauntlet
